### ISSUE TITLE
Friend Create non supported text files

### ISSUE THREAD

**Issue by 344Clinton** [FriendUPCloud/friendup#100]
Friend Create should open non-supported text files as plain text, and syntax should be selectable. For example. OpenHab uses ".items", ".rules", ".sitemap" files which have Java-like syntax. Friend Create won't even open them as plain text files.

**Comment by titlestad** [comment]
Agreed. I'll look for an implementation that verifies that the file is non-binary.

**Comment by 344Clinton** [comment]
I enabled generic file opening in artisan.js Didn't check for non-binary file type. That should be done separate from file name extension. I've never used an editor that does.
