### ISSUE TITLE
Service Unavailable The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

### ISSUE THREAD

**Issue by markyg3000** [FriendUPCloud/friendup#107]
im a new user.
everytime I try to log in I get the message below:
happens in all browsers in windows 10.

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

this is the link sent to me : https://my.friendup.cloud/

**Comment by titlestad** [comment]
The new server will be up soon - with backups, monitoring and the latest version of Friend. Watch our website and our channels (e.g. Discord) for news :-)
