### ISSUE TITLE
Documentation \ Not Available \ 404 Page

### ISSUE THREAD

**Issue by pyrosyndicate** [FriendUPCloud/friendup#109]
When trying to access any of the Documentation within the demo site you are faced with a 404 page.

![7](https://user-images.githubusercontent.com/33336125/60732335-a3203b80-9f41-11e9-89f0-f4b3611754c5.png)
![6](https://user-images.githubusercontent.com/33336125/60732336-a3203b80-9f41-11e9-8fe7-de8918434b29.PNG)

**Comment by titlestad** [comment]
This feature has now been removed.
