### ISSUE TITLE
Feature Request: Docker image

### ISSUE THREAD

**Issue by xet7** [FriendUPCloud/friendup#113]
Some starting points for any contributor for Docker image are here:
- https://github.com/Aperture-Development/friendup-docker
- https://github.com/rabejens/docker-friendup

[`install.sh` script modifications to get Friend installed on Ubuntu 18.04](https://github.com/Aperture-Development/friendup/commit/c18494f9e42cf4ba96c572ef66fa007ddcc8c284)

In general, to get Friend installed on other distros than Ubuntu 16.04, install log needs to be checked and add missing dependencies and distro version detection.

Tasks for any contributor:
- [ ] Add Ubuntu 18.04 changes and distro detection as pull request do dev branch
- [ ] Add to `install.sh` default values and optional parameter `$1` like `./install.sh autoinstall` so that installing happends without prompts. This is required for building Docker image.
- [ ] Modify Dockerfile etc to add anything else that's still missing.

**Comment by ApertureDevelopment** [comment]
Finished, full docker image and instructions are avaiable here:
https://github.com/Aperture-Development/friendup-docker

Docker Image updates automatically on a push to the Master Branch
