### ISSUE TITLE
Samba Storage on dev branch Mount Errors

### ISSUE THREAD

**Issue by 344Clinton** [FriendUPCloud/friendup#116]
Trying to add a samba drive in my dev branch installation. Log gives me:

PHP Notice:  Undefined property: stdClass::$FCOnLocalhost in /home/craig/friendup/build/modules/system/include/sandbox.php on line 96
PHP Notice:  Undefined property: stdClass::$userid in /home/craig/friendup/build/modules/system/include/editfilesystem.php on line 6
PHP Notice:  Undefined property: stdClass::$Workgroup in /home/craig/friendup/build/modules/system/include/editfilesystem.php on line 28
PHP Notice:  Only variables should be passed by reference in /home/craig/friendup/build/modules/system/include/editfilesystem.php on line 43
PHP Notice:  Only variables should be passed by reference in /home/craig/friendup/build/modules/system/include/editfilesystem.php on line 43
PHP Notice:  Undefined property: stdClass::$KeysID in /home/craig/friendup/build/modules/system/include/editfilesystem.php on line 53
PHP Notice:  Undefined property: stdClass::$userid in /home/craig/friendup/build/modules/system/module.php on line 862

Drive shows up as disconnected

**Comment by titlestad** [comment]
Let's focus on the master branch now :-)

**Comment by 344Clinton** [comment]
Already have :-)
