### ISSUE TITLE
Can't Add Device Information in dev branch

### ISSUE THREAD

**Issue by 344Clinton** [FriendUPCloud/friendup#117]
Trying to add device information in "My Account"

Feedback in system tray indicates success, but when I re-enter the window, it is not remembered
Log

> PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /home/craig/friendup/build/modules/system/include/setsetting.php:18
Stack trace:
#0 /home/craig/friendup/build/modules/system/module.php(1900): require()
#1 {main}
  thrown in /home/craig/friendup/build/modules/system/include/setsetting.php on line 18
PHP Notice:  Only variables should be passed by reference in /home/craig/friendup/build/php/friend.php on line 198
PHP Notice:  Only variables should be passed by reference in /home/craig/friendup/build/php/friend.php on line 200
PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /home/craig/friendup/build/modules/system/include/setsetting.php:18
Stack trace:
#0 /home/craig/friendup/build/modules/system/module.php(1900): require()
#1 {main}
  thrown in /home/craig/friendup/build/modules/system/include/setsetting.php on line 18
PHP Notice:  Only variables should be passed by reference in /home/craig/friendup/build/php/friend.php on line 198
PHP Notice:  Only variables should be passed by reference in /home/craig/friendup/build/php/friend.php on line 200
>

**Comment by titlestad** [comment]
Hmm, which PHP version are you running?

**Comment by 344Clinton** [comment]
> php -v
PHP 7.2.19-0ubuntu0.18.04.1 (cli) (built: Jun  4 2019 14:48:12) ( NTS )
Zend Engine v3.2.0,  with Zend OPcache v7.2.19-0ubuntu0.18.04.1,

**Comment by titlestad** [comment]
Has there been any changes in the last version of the master branch?

**Comment by titlestad** [comment]
Let's focus on the master branch from now on. :-)
