### ISSUE TITLE
Feature Request: Login to FriendSky Android app without giving permissions.

### ISSUE THREAD

**Issue by xet7** [FriendUPCloud/friendup#118]
Hi,
when I login to FriendSky Android App, it asks for permissions:
- Take photos and record video
- Record audio
- Access images, media and files

Please make it possible to login to Friend without giving any permissions. In that case, Friend should only show those images etc that are at Friend cloud, and not access any local camera/mic/files.

For example, Facebook and Messager Android apps do work without giving any permissions. When some permission is needed, I can temporarily allow it, and then disallow it, and Facebook and Messenger are still logged in.

**Comment by xet7** [comment]
The use case for me is, I would not like that if I'm chatting at FriendSky app, and someone starts video conference, and I don't happen to wear enough clothes.

**Comment by thomaswollburg** [comment]
We made a choice to require the permissions early on to avoid having to triple check eventual problems with users at a later point that can be the result of missing permissions. We will take your request into consideration for a future version of the app. As this is more a change request then an issue I will close this and transfer it to our internal app backlog.
