### ISSUE TITLE
Friend Sky Android - Multiple Notifications for Friend Chat

### ISSUE THREAD

**Issue by 344Clinton** [FriendUPCloud/friendup#119]
Running Friend Sky Android give a separate notification for each message. Notifications should be grouped.

Running nexus 5x on ver 8.1.0

**Comment by stefkosdev** [comment]
Right now app is grouping by channels (rooms or persons) from which messages are coming.
Please provide screenshot.

**Comment by 344Clinton** [comment]
Here's a couple. First is from my lock screen. Second is from my main pull down. Each notification is comprised of one or more messages.

![Screenshot_20190904-040829](https://user-images.githubusercontent.com/15161178/64256478-68eb0000-ced8-11e9-99c8-6aa8e7e578f5.png)

![Screenshot_20190904-040840](https://user-images.githubusercontent.com/15161178/64256498-77391c00-ced8-11e9-96fa-3a47aa06b19c.png)

**Comment by stefkosdev** [comment]
Can you also show me notification channels created by FriendUP app?

**Comment by stefkosdev** [comment]
Ok second thing. Seems you are using FriendUP app to login into friendsky. Please run app and logout and then use FriendSky app with friendsky.cloud server.
You can also provide me versions of FriendUP/FriendSky app.

**Comment by 344Clinton** [comment]
Hmmm... You are correct. I do have the previous FriendUP app installed, but have not used it for quite a while. I just uninstalled it and will recheck the notifications. It'll probably be tomorrow as my time is a bit out sync with everyone else's 😀

**Comment by 344Clinton** [comment]
Okay. I uninstalled the old FriendUP app and restarted my phone. Ran Fried Sky and Friendchat, and returned to the main home screen. I am running Android 8.1.0 on a nexus 5x and Friend Sky ver 0.6.5. Friend chat is grouped, but there are multiple groups.

Here is what I get for notifications....
Lock Screen
![Screenshot_20190904-121136](https://user-images.githubusercontent.com/15161178/64298609-0a9b3d00-cf2b-11e9-8052-1d3e7f3922e6.png)

Pulldown
![Screenshot_20190904-121206](https://user-images.githubusercontent.com/15161178/64298622-15ee6880-cf2b-11e9-90f2-f876e6c4aa5f.png)

**Comment by stefkosdev** [comment]
Ok seems you never logout from FriendUP app and your appid is still in our database. This leads to message "Application was removed by system". I will come back to you when fix will be ready. Regarding groupping, please make screenshot with application notification channels.

**Comment by 344Clinton** [comment]
Hey stefkosdev. As long as the error makes sense to you😀. Above my head! I'm afraid I don't quite understand what you mean by "screenshot of application notification channels". Don't the screenshots above show that? I do have an app notification settings under my android settings. Do you mean that?

**Comment by stefkosdev** [comment]
Take a look:
https://www.financialexpress.com/industry/technology/whatsapp-v2-18-18-notification-channels-android-oreo/1024928/
As you see each app can create own notification channels (from Android 8). I want to know if app created more channels then it should (doubles).
We will probably register two bugs in our own ticket system. Of course during fixing we will try to deliver some information here.

**Comment by stefkosdev** [comment]
We are testing now final fix.

**Comment by 344Clinton** [comment]
Sorry stefkosdev, I've been away for a bit. Do you still need some screen shots?

**Comment by stefkosdev** [comment]
No, thanks for your help.

**Comment by 344Clinton** [comment]
All seems good now!
