### ISSUE TITLE
Friend Sky - JukeBox - Pause, Stop Control Issues

### ISSUE THREAD

**Issue by 344Clinton** [FriendUPCloud/friendup#121]
Made a simple two song playlist. Start playing one song. Press "pause" or "stop". next song starts playing. Only way to stop music is to close app.

Don't know which version as there is no version number

**Comment by titlestad** [comment]
Hmm, ok. I will add a version number and see if I can reproduce. Little bit undersupported this app - but now that more than me is using the app, perhaps we should add a roadmap for it? I definately want to integrate it with a podcasting service.

**Comment by titlestad** [comment]
This app is now getting a new development effort - hopefully we will get this fixed by v1.2.4 :)

**Comment by titlestad** [comment]
This has now been fixed. :) In latest master.
