### ISSUE TITLE
When I try to edit language in the FriendCreate IDE, it just goes back to PHP

### ISSUE THREAD

**Issue by KaareBo** [FriendUPCloud/friendup#123]

**Comment by titlestad** [comment]
Hello! We will take a look at this. Friend Create hasn't seen as much activity as we would want lately. But we'll take a look at this and see if there's a quick fix. In the meantime, if you are building a Friend project - I'd suggest you use your local IDE with the Friend codebase from github.

Thanks for the hat tip.

**Comment by titlestad** [comment]
Friend Create v2.0 fixes this issue :-)
