### ISSUE TITLE
Issues getting set up

### ISSUE THREAD

**Issue by coreybruce** [FriendUPCloud/friendup#124]
```
Setting up Friend Core database.
ERROR 1146 (42S02) at line 1: Table 'mysql.user' doesn't exist
Setting up user: friendup
Creating database: friendup
ERROR 1006 (HY000) at line 1: Can't create database 'friendup' (errno: 2 "No such file or directory")
Creating tables
ERROR 1049 (42000): Unknown database 'friendup'

Building Friend Core.
This can take up to several minutes depending on your machine.
Compilation log can be found in /mnt/Storage/Corey/friendup/compilation.log
```

Also the setup doesn't go through asking to set the root password for mysql but than asks for it even tho you never setup one.

**Comment by titlestad** [comment]
Hello, building Friend right now is a manual process - due to issues with the installer. We know about this and are create a debian repository instead.

If you need help compiling Friend, we urge you to get in touch with our Discord channel.

https://discord.gg/gUJUD8

**Comment by coreybruce** [comment]
Thank you for the update, I was testing this on Manjaro and was using the setup.sh file.

**Comment by titlestad** [comment]
You can now use our new documentation.
