### ISSUE TITLE
Feature Request: add full support (across all apps and core) for relative urls.

### ISSUE THREAD

**Issue by mistergibson** [FriendUPCloud/friendup#127]
So, like many I have but a SINGLE ip address upon which to hang 4 to 7 web services. This forces folks in my spot to use relative urls. What I'm asking is that instead of basing everything off of fchost variable, use a 'base_url' variable that is, by default, and empty string but can be used to generate asset links within generated html pages. So:

https://mysite.org/some_path/...

I typically accomplish what I need with SSL secured Apache reverse proxy settings: (proxy does all SSL stuff for the backend)

ProxyPass /some_path http://localhost:6502/
ProxyReversePass /some_path http://localhost:6502/

... and voila, if the server code can handle it, it works like a charm.

I of course tried this fer giggles with FriendUp and no dice. It just doesn't currently support this. I realize this would mean you have to alter the way your html pages are generated, but I contend this feature is, in the long run, very well worth the effort. I am working on a framework myself and support this - so I understand what it takes to do it.

So, I'm asking you support this style of relative url anchoring for the core and app system itself, and not require a dedicated server for it as it must share that IP with other services that I need.

Cheers, and thanks for what you've done thus far.

**Comment by thomaswollburg** [comment]
Hi, even with a single IP you should be able to use named based virtual hosting and just assign a dedicated subdomain? Like friend.mysite.org. The workspace contains quite a lot of JS code and I am not sure how a base href would affect the system - so we suggest to use name based virtual hosting. Please let us know if this is possible for you (as it was with all the different hosters we have been using so far both here and in other projects).

**Comment by mistergibson** [comment]
Could you post a sample Apache configuration here? Others will more than likely run into this as well.

Thanks in advance.

**Comment by titlestad** [comment]
Here is an example of e.g websockets and http.

<Location /myapp/>
    Order allow,deny
    Allow from all
    ProxyPass wss://someaddress.com:27970/
    ProxyPassReverse wss://someaddress.com:27970/
</Location>

<Location /myapp/>
    Order allow,deny
    Allow from all
    ProxyPass https://someaddress.com:443/
    ProxyPassReverse https://someaddress:443/
</Location>
