### ISSUE TITLE
Sharing documents in Workspace

### ISSUE THREAD

**Issue by Martintautra** [FriendUPCloud/friendup#129]
If I have a document which I want an internal or external parties to work or sign on, it could be beneficial to have an option when Right-Clicking where you can select "share-with".
e.g. it could be integrated into the Mail client, so the mail opens automatically with Attachment, or a direct link to where it can be worked on?
Hope this was explained clear?!

//Martin Tautra

**Comment by titlestad** [comment]
Yes indeed. At the very least, it should send a push notification / desktop notification to the destination user with "Martintautra shared a file with you." <newline> "Click here to access the file."

We will add it to our list of improvements. Will comment here when that is implemented.

**Comment by titlestad** [comment]
Sharing is now implemented with the shared drive.
