### ISSUE TITLE
Website's HTTPS certificate is revoked

### ISSUE THREAD

**Issue by zagrad** [FriendUPCloud/friendup#132]
The [website](https://friendos.com/)'s HTTPS certificate is revoked. It probably was a Let's Encrypt certificate which must be renewed due to the vulnaribility that was found a few days ago.

See for example https://www.cyberciti.biz/security/letsencrypt-is-revoking-certificates-on-march-4/ for more information.

**Comment by thomaswollburg** [comment]
We renewed it already.
