### ISSUE TITLE
Question: Database updates

### ISSUE THREAD

**Issue by ApertureDevelopment** [FriendUPCloud/friendup#136]
Hello FriendUP team,

I have a question regarding the SQL update scriptsm I know they are located inside the sqlupdatescripts folder, and I would like to know, is there a way to skip friend running it themself, meaning how is the DB version specified? from where do we get the database version?

I need to know that because as of right now the Docker container is broken, and to fix it I need to run the database preparations before starting friend ( https://github.com/Aperture-Development/friendup-docker/issues/9 )

Thank you and have a great day

**Comment by titlestad** [comment]
No at this time you cannot skip.
I will file an internal bug and perhaps we can somehow regulate this with a config entry or command line option.
