### ISSUE TITLE
Can't get Friend to start up at all

### ISSUE THREAD

**Issue by ApertureDevelopment** [FriendUPCloud/friendup#137]
The current Master branch seems to be broken very harshly.

I have tried following the installation manual, have verified all dependencies existing, and tried to build it multible different ways, but I always get the same result: Nothing.

The current manual at the readme does not work at all, when I start the FriendCore I dont get any log feedback at all, when I build it with the same method the docker container is built I don't get the webpage to load, I always get "Empty Responce" and when I generate the missing certificate ( as stated from the logs, it expects a certificate in cfg/crt/certificate.pem 9 despite all SSL settings being disabled ) I get to a point where Friend loads endlessly and never gets to a point until the browser decides that the connection timed out.

Due to that reason, which I am unable to debug or fix, and because I never got a reply on Discord, I have put the Docker project on hold until I get a reply on how to fix this bug.

**Additional Informations:**
**OS:** Ubuntu 18.04 LTS
**Dependencies:** Installed
**Database:** MySQL 8

**Comment by stefkosdev** [comment]
In latest version SSL is required.
This is line which generates certyficates for me: sudo openssl req -newkey rsa:2048 -nodes -sha512 -x509 -days 3650 -nodes -out "build/cfg/crt/certificate.pem" -keyout "build/cfg/crt/key.pem"
Please try this.
In free time I will try to fix this bug, I mean Fcore should always run.

**Comment by ApertureDevelopment** [comment]
Still doesn't work. I only get as far as 
```
root@ubuntu-friendup:~/friendup/build# ./FriendCore
 (system/fsysdyn/fsysssh2.c:175) 140301341439808 LIBSSH init 0
  (system/fsysdyn/fsysssh2.c:182) 140301341439808 [SSH2FS] init
```

STrace also reports a ton of not found errors, such as:
```
openat(AT_FDCWD, "/home/ubuntu/friendup/build/mysql.library", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

tho I have verified the file exists

**Comment by ApertureDevelopment** [comment]
So the bug seems to be with "make release" somehow when I try to make the release it doesn't startup at all, thought when I build the compile, it starts up fine.

**Comment by stefkosdev** [comment]
"make release" compile Friend in release mode. So you will not get too much debug from FriendCore.
As you already know you should do "make clean setup compile install", go to build directory, launch FriendCore. Then you will see all debug output in your console.
And as we talked on discord channel, right now you cannot run FriendCore without SSL. I will register issue now in our private bug tracker and fix.

**Comment by stefkosdev** [comment]
Fixed in branch: patch/fcore_without_ssl
