### ISSUE TITLE
Storage size is not set

### ISSUE THREAD

**Issue by ApertureDevelopment** [FriendUPCloud/friendup#138]
By default the storage size of "Home" seems to not be set, causing issues with the whole data storage system. I am unable to save or delete any data from the disk, it doesn't even show up by default.

**How to Reproduce:**
1. Install Friend
2. Login
Storage "Home" is not showing up

If you change the size manually it suddenly pops up

**When logging in:**
![Screenshot (48)](https://user-images.githubusercontent.com/16450982/97813160-8fe0c580-1c86-11eb-8424-63c307a11ccd.png)

**Size of the volume by default:**
![Screenshot (49)](https://user-images.githubusercontent.com/16450982/97813161-940ce300-1c86-11eb-9da5-860e9201cf92.png)

**Home storage shows up when setting the size manually**
![Screenshot (50)](https://user-images.githubusercontent.com/16450982/97813163-95d6a680-1c86-11eb-8bfb-ee2e0f37cf7a.png)

**Comment by stefkosdev** [comment]
This bug was fixed. Please check with latest code.
