### ISSUE TITLE
Unable to compile ....

### ISSUE THREAD

**Issue by whittinghamj** [FriendUPCloud/friendup#139]
I cloned the repo, entered the folder and typed 'make' and got the following error message ....

root@ubuntu /opt/friendup # make
Making default compilation with debug.
make -C core DEBUG=1 WEBSOCKETS_THREADS=1 USE_SELECT=0 NO_VALGRIND=0 CYGWIN_BUILD=0 USE_SSH_THREADS_LIB=1 LOG_TIMESTAMP= OPENSSL_INTERNAL=1 ENABLE_SSH=0
make[1]: Entering directory '/opt/friendup/core'
Compile ...
gcc -DFRIENDUP=1 -DMUTEX_TIMEOUT_TIME=500000 -D_POSIX_C_SOURCE=199309L -D__need_timespec -D__USE_XOPEN2K -DAPPDATE=\"20201103_061930\" -DAPPVERSION=\""v1.2.5"\" -DAPPGITVERSION=\"Hydrogen-473-g7998f8eb3\" -D_XOPEN_SOURCE=600 --std=c99 -Wall -W -D_FILE_OFFSET_BITS=64 -fPIC -Wno-unused -Wno-unused-parameter -I/usr/include/mysql  -D__USE_POSIX -I/usr/include/libxml2/ -D_FILE_OFFSET_BITS=64 -DENABLE_SSL -g -DMOD_TIMEOUT=45 -DFILESYSTEM_MOD_TIMEOUT=400 -DMOD_NUMBER_TRIES=1 -DMUTEX_TIMEOUT_NUMBER_TRIES=30  -I../libs/ -I../libs-ext/libwebsockets/build/include/ -I. -I/usr/include/mysql  -I..//usr/include/libxml2/ -I/usr/include/samba-4.0/  -I../libs-ext/libssh2/include/ -I../libs-ext/openssl/include/ -D__DEBUG -O0 -g -DENABLE_WEBSOCKETS_THREADS=1 -c -o obj/main.o main.c
Assembler messages:
Fatal error: can't create obj/main.o: No such file or directory
Makefile:221: recipe for target 'obj/main.o' failed
make[1]: *** [obj/main.o] Error 1
make[1]: Leaving directory '/opt/friendup/core'
Makefile:138: recipe for target 'compile' failed
make: *** [compile] Error 2

Any ideas?

**Comment by ApertureDevelopment** [comment]
Use ``make setup compile`` instead of just make
