### ISSUE TITLE
Window positions are not remembered

### ISSUE THREAD

**Issue by idontbyte** [FriendUPCloud/friendup#14]
The window positions that you have set during your session are lost on reload.
I think this should only be remembered on your current browser as each of your devices probably has a different resolution.

**Comment by thomaswollburg** [comment]
Hi, we concur. Will add this to our backlog. Asking you as a user: how would you want directory view positions to be remembered? I think we should not do this on a per folder basis but rather per Mount and use the position of the last active window on a particular mount. What do you think?

**Comment by idontbyte** [comment]
Per folder would make sense if the folders open in a new window, but they open within the current window which is a more modern approach, so in my opinion you are spot on.

**Comment by ManuVerl** [comment]
I agree with [idontbyte](https://github.com/idontbyte)

**Comment by RAMupgrade** [comment]
Could users have an option to "Remember window positions on this device"?

**Comment by titlestad** [comment]
The window positions are remembered when you are logging out.
