### ISSUE TITLE
EMPTY_RESPONSE errors preventing access to Friend

### ISSUE THREAD

**Issue by ApertureDevelopment** [FriendUPCloud/friendup#140]
Hello,

I have experimented around with Friend for the past few weeks and found out that the EMPTY_RESPONSE errors seem to be worst with Chrome, on chrome the login window does not even load while on firefox it does load and in one out of ten times I am able to login ( I try the same password over and over and suddenly it works after a lot of attempts ). My guess would be that the issue is related to the websockets, but I am not 100% sure about it.

Thank you for reading my Bug report
MG

**Comment by titlestad** [comment]
Can you still reproduce this?

**Comment by stefkosdev** [comment]
Hey

Can you give us logs from FriendCore? console output fe.

Regards

**Comment by titlestad** [comment]
Closed due to unable to reproduce any more.
