### ISSUE TITLE
Reference to obsoleted ssh_threads prevents linking

### ISSUE THREAD

**Issue by Sirachosur** [FriendUPCloud/friendup#142]
Using Debian 10, compilation fails as ld can't find ssh_threads.  However, this library does no longer exist in libssh > 0.8, the functionality being provided by libbsh.so instead (according to my fact-checking online anyway).

Could someone point to me the file I need to edit before 'making clean' and restart the process?

the command causing the compilation (or more technically the linking) issue is :

`gcc -o bin/FriendCore obj/main.o obj/library.o obj/friend_core.o obj/thread_linux.o obj/pid_thread_manager.o obj/friendcore_manager.o obj/worker_manager.o obj/event_manager.o obj/pid_thread.o obj/friendcore_info.o obj/worker.o obj/pid_thread_web.o obj/cache_uf_manager.o obj/cache_file.o obj/cache_manager.o obj/cache_drive.o obj/cache_user_files.o obj/http_client.o obj/socket.o obj/websocket_client.o obj/cookie.o obj/uri.o obj/file_download.o obj/mime.o obj/http_file.o obj/path.o obj/user_session_websocket.o obj/digcalc.o obj/protocol_http.o obj/protocol_websocket.o obj/protocol_webdav.o obj/websocket.o obj/locfile.o obj/http.o obj/service.o obj/services_manager_web.o obj/service_manager.o obj/http_string.o obj/simple_hash.o obj/newpopen.o obj/hashmap_long.o obj/key_value_list.o obj/time.o obj/list.o obj/buffered_string_disk.o obj/hashmap.o obj/murmurhash3.o obj/element_list.o obj/list_string.o obj/file_operations.o obj/buffered_string_benchmark.o obj/friendqueue.o obj/buffered_string.o obj/sha256.o obj/md5.o obj/base64.o obj/json_core.o obj/list_string_disk.o obj/friendstring.o obj/string.o obj/friendstringarray.o obj/session_id.o obj/rootclass.o obj/class.o obj/phpproxyclass.o obj/mainclass.o obj/ssh_server.o obj/machine_info.o obj/network.o obj/web_util.o obj/systembase.o obj/systembase_web.o obj/command.o obj/dictionary.o obj/module.o obj/device_handling.o obj/device_manager_web.o obj/door_notification.o obj/file.o obj/fs_remote_manager_web.o obj/fsys.o obj/fs_manager.o obj/file_permission.o obj/fs_manager_web.o obj/dosdriver.o obj/fsys_activity.o obj/json_converter.o obj/jsmn.o obj/json.o obj/remote_user.o obj/user.o obj/user_manager_remote.o obj/user_mobile_app.o obj/user_application.o obj/user_manager.o obj/user_manager_web.o obj/user_sessionmanager.o obj/user_session.o obj/log.o obj/inramfs.o obj/invar_manager.o obj/invar_manager_web.o obj/invar.o obj/app_permission.o obj/application_manager.o obj/application_web.o obj/authmodule.o obj/usb_manager.o obj/usb_device.o obj/usb_device_web.o obj/printer_web.o obj/printer_manager.o obj/printer.o obj/png.o obj/image.o obj/user_logger.o obj/user_logger_manager.o obj/admin_web.o obj/admin_manager.o obj/comm_service.o obj/comm_service_client.o obj/comm_service_parsers.o obj/comm_msg.o obj/cluster_node.o obj/comm_service_select.o obj/comm_service_remote.o obj/autotask.o obj/dos_token_manager.o obj/token_web.o obj/dos_token.o obj/websocket_apns_connector.o obj/websocket_req_manager.o obj/websocket_req.o obj/connection_info.o obj/fkey_manager.o obj/fkey.o obj/server_checker.o obj/webdav_token_manager.o obj/webdav_token.o obj/connection_web.o obj/mobile_app.o obj/notifications_sink.o obj/mutex_manager.o obj/user_session_app_manager_web.o obj/user_session_app.o obj/mobile_manager.o obj/mobile_app_connection.o obj/mobile_list_entry.o obj/mobile_web.o obj/calendar_manager.o obj/calendar_entry.o obj/calendar_event.o obj/properties.o obj/dictionary_ini.o obj/iniparser.o obj/notification_sent.o obj/notification_manager.o obj/notification_manager_ios.o obj/notification_manager_web.o obj/notification.o obj/notification_manager_android.o obj/user_group_manager_web.o obj/user_group.o obj/user_group_manager.o obj/permission_manager.o obj/role_manager.o obj/security_manager.o obj/sas_manager.o obj/sas_session.o obj/sas_web.o obj/service_manager_web.o  ../libs-ext/libwebsockets/build/lib//libwebsockets.a -Lsystem/bin/ -lm -lrt -lmagic -lxml2 -lmysqlclient -lpthread -lz -lm -lrt -latomic  -lgd -lpng -lz -ljpeg -luv ../libs-ext/openssl/libssl.a ../libs-ext/openssl/libcrypto.a -ldl -lpthread -lstdc++ -lssh_threads -Wl,--export-dynamic`

Thanks and best regards

**Comment by titlestad** [comment]
This one is fixed in the Ubuntu 20 documentation.
