### ISSUE TITLE
Unable to add New User on fresh database

### ISSUE THREAD

**Issue by GloomyJD** [FriendUPCloud/friendup#143]
I followed the setup steps and have successfully got FriendOS running on Ubuntu 20.04, however I am unable to add a New User from the 'Users' settings page.

Clicking New User does nothing, and there looks to be an invalid 'N/A' user present. See attached screenshot.
Recreated in both Edge 90.0 and Safari 14.0.3.

I have attempted to completely remove and recreate the database, which has not changed anything.
<img width="682" alt="Screenshot 2021-05-18 at 00 01 42" src="https://user-images.githubusercontent.com/11637968/118566681-3f394180-b76c-11eb-9764-9f69427619e1.png">

Setup steps used:
https://docs.friendos.com/docs/administrator-guide/installation-ubuntu-20/

**Comment by stefkosdev** [comment]
Hey. Please use System app to create accounts. Users app may not work and we will remove it shortly.

**Comment by masterdanzh** [comment]
Using the System app do not help: 
<img width="1405" alt="Screenshot 2021-05-29 at 02 01 34 " src="https://user-images.githubusercontent.com/60588173/120051680-dd0cf600-c021-11eb-9d06-5d17ce619739.png">

**Comment by stefkosdev** [comment]
Ok last question from my side.
So whats happening when you press "save" (create user)?
Can you check Chrome console (network tab) whats happening with call? I think I saw this bug and it was related to curl.

**Comment by titlestad** [comment]
Is this still a problem or should we close the issue? @stefkosdev

**Comment by titlestad** [comment]
@masterdanzh Could you try with the release/1.2.6 branch?
We will merge this one into master shortly.

**Comment by titlestad** [comment]
Closed, fixed in release/1.2.6
