### ISSUE TITLE
how do i run my windows apps and visit the friend store???

### ISSUE THREAD

**Issue by jason-1001** [FriendUPCloud/friendup#158]
![MergedImages](https://user-images.githubusercontent.com/90665508/170391908-0a58134f-80db-47b4-b3ce-bf85dd50f9da.png)
i saw these friend os videos:
[https://www.youtube.com/watch?v=2ZlPdo-m3oM](url)
the one that mentions the friend os store

[https://www.youtube.com/watch?v=IRMhb_2nKPM](url)
[https://youtu.be/HCuPOp1dx9E](url)

and these two videos showed us that you can run applications on friend os

the question is.... how? how one could run an app in friend os and utilize friend os's app store?

**Comment by titlestad** [comment]
To use Windows apps, you need to use Liberator, Friend's adaptation of Guacamole and FreeRDP. But these haven't been released as open source yet. As for the web store, it has been postponed.
