### ISSUE TITLE
Browser extension to load FriendOS on the client side for faster loading and better security

### ISSUE THREAD

**Issue by Destroyinator69420** [FriendUPCloud/friendup#159]
Will there ever be a FriendOS browser extension to load FriendOS as a client side web app? This would improve loading times and increase security, since more control is placed in the hands of the user. This approach is very similar to mega.nz, which allows users to load the mega interface locally to improve security, and this works since the client is loaded locally, the private key is safe with the device, and website is harder to compromise by feds or hackers. When will FriendOS do something similar?

**Comment by titlestad** [comment]
Yeah, we're working on FriendOS "2.0" which will have a revised and improved security model. The extension work may happen some time in development of that.

**Comment by titlestad** [comment]
Right now, we have a PWA, and for now this will kind-of fulfill the "extension" side of things. If you go to Friend Sky (you can obtain an account on https://friendos.com), you can install via Chrome.
