### ISSUE TITLE
Huge list of Apps you could add to FriendOS

### ISSUE THREAD

**Issue by anonimo82** [FriendUPCloud/friendup#160]
@titlestad 
Hello everyone.
Please, consider adding these web Apps to your arsenal.
Many of them are not (yet?) mobile ready, but maybe you can convince the suthor(s) to make it mobile friendly (?)

Since I update the list frequently, instead of posting here every time, I'll paste a link to it.
Here it is: [The OnTheCloud App list](https://docs.google.com/spreadsheets/d/1TuwccGwehWq-ojF5zDVrK2hJxPub9bGjPm2DxeipRHs/edit?usp=drivesdk)

Thanks for any help.

**Comment by arrighettai** [comment]
I checked, these are not mobile ready:
- BoxySVG
- PixTeller
- Marq
- BestSnip
- LucidChart
- Audiotool
- Gantt.io
- Clara.io
- WebGLStudio
- C

**Comment by arrighettai** [comment]
P.S.: Also do note, the Google Drive AddOns won't work on mobile, because both the App and the website deny you to create anything but a spreadsheet, a document or a presentation. A drawing is neither allowed, so to speak.

We've to hope this will change, but I'm afraid it won't.

**Comment by arrighettai** [comment]
P.P.S.: Grubba looks promising, but how can we try it?

**Comment by anonimo82** [comment]
I changed some Apps, please, check back

**Comment by arrighettai** [comment]
Mozello is cool, like Google Sites on steroids, plus it's mobile friendly.
Paiza is nice, mobile friendly except for the text editor, unless you maximize it. It also support minimal autocomplete (no SVG/MathML markup, no JavaScript support) for HTML/CSS/PHP.
The cool side of Paiza is that you can have a server set up with a couple clicks, then develop on it.
I only tried PHP, but looks god. Worth a try.

**Comment by stefkosdev** [comment]
Sorry for lack of answer/word. We have small team and currently busy with some tasks.
Is there a place from where we can get this apps? Or this is just wish-list?

**Comment by anonimo82** [comment]
It's just a wish list, but all of them are websites and almost all provide contact info for the developer(s)

**Comment by anonimo82** [comment]
By the way, FriendOS mobile version doesn't have the menu, which is very limiting

**Comment by arrighettai** [comment]
> Sorry for lack of answer/word. We have small team and currently busy with some tasks. Is there a place from where we can get this apps? Or this is just wish-list?

Trust me, having a look at the list is worth the time it takes

**Comment by anonimo82** [comment]
I've replaced Paiza cloud with Phoenix editor and Online convert with Aspose.
Check back. @stefkosdev note I consider the list huge, but it's subjective: there are 60 items, more or less

**Comment by anonimo82** [comment]
I updated the list once more, this time (I hope) for the last time.
I added informations such as "is the website responsive?" "does the developer offer a mobile/desktop App?" and "does the web App keep my work on their server?".

I hope you enjoy my work, and I seriously hope you'll consider adding these Apps to FriendSky.

Thanks for either.

**Comment by chiaravalle** [comment]
Your list is not available, please, update the URL.
Meanwhile, inspired by your work, I wrote a list too.
It's here: https://docs.google.com/spreadsheets/d/1D93GxQwzdhzopJt0e8Jm2Twl6DhPszRA/edit?usp=drivesdk&ouid=103732428494828655417&rtpof=true&sd=true

But it's not only cloud oriented

**Comment by titlestad** [comment]
> Your list is not available, please, update the URL[...]
> 
> But it's not only cloud oriented

These apps won't be running in the short term for Friend OS, as they aren't web apps. But with our XPRA integration and our network storage support, and perhaps some available Linux server, they could be streamed in the future.

I want to close this thread as it is out of date, but I'd love to see @anonimo82 add an updated list, now that Friend Sky has been reignited.

**Comment by chiaravalle** [comment]
Hello. You misunderstood me, I was just pointing out the fact my list is multi platform, but I never meant such platforms should be supported/included in Friend.
Plus, each section of my list, include only software which, in the free version, is not (IMHO) too limited (in the worse case), or is free at all.

If you're interested, I also have something similar with only Google Drive AddOns.
Because of my own rules of inclusion in the list, it lacks a lot of stuff.

Let me know.

Regards, have a good day =)
