### ISSUE TITLE
upload percentage not accurate

### ISSUE THREAD

**Issue by SquareCereal724** [FriendUPCloud/friendup#166]
this file finishes the upload at 47%

**Comment by SquareCereal724** [comment]
https://github.com/FriendUPCloud/friendup/assets/83764123/3ab61b84-c702-4c52-9d89-5ca237997d40

**Comment by titlestad** [comment]
This looks like it's happening when the upload is somehow being done twice at the same time due to a js error. Fix in testing.

**Comment by SquareCereal724** [comment]
Still not fixed.
