### ISSUE TITLE
The "Open with" property of a file doesn't work.

### ISSUE THREAD

**Issue by steffest** [FriendUPCloud/friendup#170]
Steps to reproduce:

- Create or upload a .txt file
- Double click it (I would expect this to open "Author" but the instead the file gets downloaded, but alas)
- Right click the File and select "properties"
- Change the "Open With(.txt) dropdown to "Author"
- Press "Save"
- Double click the file

Result: The file is downloaded
Expected; the file is opened with Author

**Comment by titlestad** [comment]
Actually it does work, but you need to reload the workspace. This bug is filed in our internal bug repository and will be fixed before the release of 1.3.0. I will track this one and close it as soon as it's fixed.

**Comment by titlestad** [comment]
It's now fixed. :-) Also available on Friend Sky now.
