### ISSUE TITLE
"New Memo" silently overwrite "new_memo.memo" if it already exists

### ISSUE THREAD

**Issue by steffest** [FriendUPCloud/friendup#171]
Steps to reproduce

- Right click into a folder in "Files"
- Select "New memo"
- open the file new_memo.memo and type some content
- save the file and close it
-  Right click into the same folder in "Files"
- Select "New memo"

Result: the first "new_memo.memo" file is overwritten with a new blank file
Expected: at least a warning or ideally a  " new_memo2.memo" file

**Comment by titlestad** [comment]
Fixed this - it now makes sure it's properly named (new_memo_2.memo, new_memo_3.memo etc). Also on Friend Sky.
