### ISSUE TITLE
Context menu sometimes in wrong context

### ISSUE THREAD

**Issue by steffest** [FriendUPCloud/friendup#172]
Steps to reproduce

- Go to "Files"
- right click a file and select "Properties"
- right click somewhere in the "Properties" window
-  select "new memo"

Result; an error in the console: Cannot read property "Path" of undefined and no new memo.
Expected; Context menus to display meaningful actions from its context

**Comment by titlestad** [comment]
I fixed this in the 1.3.0 branch. Friend Sky was updated.
