### ISSUE TITLE
Unable to access web portal

### ISSUE THREAD

**Issue by johncarterofmars** [FriendUPCloud/friendup#186]
Hello. I have FriendOS installed in a Proxmox VM running Ubuntu 20.04. I created the cfg.ini and everything was made and installed. I am able to run the app and it starts. However, the web portal isn't available. When I ssh into the VM and run ss-tulpn4, it only shows the MySQL, SSH, and DNS ports listening. 
This is the output at the console after starting:

140209841575808: (core/friend_core.c 2222) =========================================
140209841575808: (core/friend_core.c 2223) ==========Starting FriendCore.===========
140209841575808: (core/friend_core.c 2224) =========================================
 (core/friend_core.c:2297) 140209841575808 [FriendCoreRun] Listening.
 (core/friend_core.c:1823) 140209841575808 [FriendCoreEpoll] start
 (core/event_manager.c:357) 140209796019968 [EventManager] Start thread 0x56120df0f74b  SB ptr 0x56120f1dc030 event name: CommServicePING
 (core/event_manager.c:363) 140209796019968 [EventManager] Thread started
 (communication/comm_service.c:1902) 140209762170624 bad resp 0
 (communication/comm_service.c:1943) 140209762170624 [ServiceTempThread] internal ping thread quit
 (core/event_manager.c:167) 140209770563328 [EventLaunch] quit
 (communication/comm_service.c:1902) 140209753745152 bad resp 0
 (communication/comm_service.c:1943) 140209753745152 [ServiceTempThread] internal ping thread quit

Any suggestions on how to get this running? 
Thank you.

**Comment by titlestad** [comment]
Hey. By default, Friend OS runs on port 6502. So if you've just configured it, you should be able to access it here:

http://localhost:6502/webclient/index.html

Normally - a Friend OS system is run as a user, and then a proxy, like Apache2, can run on port 443/80 to forward to FriendCore.

**Comment by johncarterofmars** [comment]
Thank you. I am running internally at the moment on a Proxmox hypervisor. When I launch the IP:6502 in my browser, I can see that the page will change as if its trying to load. Eventually it will time out.

If I look at the console at that time, I see the following:
![ksnip_20231025-152444](https://github.com/FriendUPCloud/friendup/assets/17039716/ec4bbe46-ead5-4192-b9f0-b16e4ba6fb11)

Any suggestions? I appreciate it.

**Comment by titlestad** [comment]
Hmm, perhaps you have the wrong address - looks like it is getting to a place that does not exist (catch_all.php).

Try IP:6502/webclient/index.html and see if that works?

**Comment by titlestad** [comment]
Stale.
