### ISSUE TITLE
Suggestion: LDAP authentication

### ISSUE THREAD

**Issue by rabejens** [FriendUPCloud/friendup#23]
I just got FriendUP to work with Docker, [here is the page for the container on Github][1] and [here is the page in the Docker hub][2].

With this, it is possible to run it on NAS devices like the Synology series with minimal effort as they have Docker well integrated.

Currently, user accounts are local to FriendUP but for using on NAS devices, it would be great if one could integrate it into the user accounts that need to be created anyway. At least Synology supports OpenLDAP so I'd consider LDAP authentication a feasible way to accomplish this (and to get integration into other infrastructures like MS ActiveDirectory nearly for free).

[1]: https://github.com/rabejens/docker-friendup
[2]: https://hub.docker.com/r/windfisch/friendup/

**Comment by titlestad** [comment]
We do have auth module support, so if you'd like to have a go, say, and we'll get you all the documentation you need.

**Comment by rabejens** [comment]
Unfortunately, my LDAP knowledge is not sufficient for me to write a client library.

**Comment by titlestad** [comment]
It will be done anyway. We do have SAML support in Friend now. But we're still customizing this.

**Comment by titlestad** [comment]
SAML can use LDAP via ADFS right now. In fact, I wouldn't be surprised if our SAML module could be made to talk to LDAP already. Marking as fixed.
