### ISSUE TITLE
friendup install.sh: use existing MySQL DB on remote host

### ISSUE THREAD

**Issue by ghost** [FriendUPCloud/friendup#35]
Hi!

After checking out friendup some minutes ago and executing ./install.sh the installer asks me to confirm the installation of local mysql DB on localhost. 

It would be better to first ask the user if he wants to use a database on remote server or if he wants to install a database locally on that host. 

Second, you cannot not confirm the request, as it will bring you back to the exact same dialog requester.

**Comment by titlestad** [comment]
Not using install.sh anymore.
