### ISSUE TITLE
install.sh: illegal mysql password

### ISSUE THREAD

**Issue by ghost** [FriendUPCloud/friendup#36]
After proceeding with local mysql DB installation and denying Friend Network & Friend Chat installation because lack of turn server, installer proceed with error: 

Illegal mysql password, please try again.

**Comment by ingoj** [comment]
... and it gets stuck at this point. Confirming the error with "OK" brings up the error again.

**Comment by titlestad** [comment]
We haven't been able to reproduce this bug. Is it still occuring?

**Comment by titlestad** [comment]
Not using install.sh anymore.
