### ISSUE TITLE
make clean setup release install is not rebuilding FriendCore

### ISSUE THREAD

**Issue by dambaev** [FriendUPCloud/friendup#43]
Hi,
I am experimenting with friendup and I had installed v1.0 at Jan 7. Today I had updated it to 1.1 and install.sh proposed to run "make clean setup release install" instead, which I had done.
But looks like FriendCore haven't been changed:
```
odroid@odroid64:~/friendup$ stat /opt/friendup/FriendCore 
  File: '/opt/friendup/FriendCore'
  Size: 4926928   	Blocks: 9624       IO Block: 4096   regular file
Device: b302h/45826d	Inode: 553090      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-01-07 11:28:33.898449857 -0500
Modify: **2018-01-07** 11:28:33.918450484 -0500
Change: 2018-01-07 11:28:33.918450484 -0500
 Birth: -
```

In order to walkaround, I had to do clean install

**Comment by stefkosdev** [comment]
Can you post somewhere compilation.log ?

**Comment by stefkosdev** [comment]
If you had problems with websockets lib then you can check my latest changes. Please give me feedback if they worked for you.
