### ISSUE TITLE
Shell: info command doesn't work

### ISSUE THREAD

**Issue by warpdesign** [FriendUPCloud/friendup#45]
How to reproduce?
- open a shell
- type info

Nothing happens. The console shows this error:

> oo.js:31751 Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at window.Shell.execute (oo.js:31751)
    at window.Shell.executeEvaluateInput (oo.js:31151)
    at oo.js:30318

**Comment by arturlangner** [comment]
Thank you - bug confirmed. Internal reference BG-545.

**Comment by titlestad** [comment]
This was fixed. :)
