### ISSUE TITLE
UX: problems dragging screen down when in fullscreen

### ISSUE THREAD

**Issue by warpdesign** [FriendUPCloud/friendup#46]
How to reproduce?
- switch the browser to fullscreen mode (f11 in Chrome/Windows)
- move the mouse to the top of the screen
- press left mouse and try to move the screen down

What happens?
Nothing happens.

What should happen?
Screen should be dragged down.

**Note:** moving the mouse a single pixel below the top of the screen before trying to drag the screen seems to be enough to make it work.

**Comment by titlestad** [comment]
Thanks for finding this! I'll take a look.

**Comment by titlestad** [comment]
Has been fixed in later releases.
