### ISSUE TITLE
Installation on Debian 9 fails

### ISSUE THREAD

**Issue by dm8tbr** [FriendUPCloud/friendup#5]
Excuse the crude output. Running install.sh inside `screen -L` was the quickest way to get output logged that otherwise would have been unreachable after the script terminated.

Relevant output follows:

> debian distro found
> VERSION_ID="9"
> version 9
> 
> =====Installing dependencies...
> =========================================================
> ^MReading package lists... 0%^MReading package lists... 100%^MReading package lists... Done
> ^MBuilding dependency tree... 0%^MBuilding dependency tree... 0%^MBuilding dependency tree... 50%^MBuilding dependency tree... 50%^MBuilding dependency tree       
> ^MReading state information... 0%^MReading state information... 0%^MReading state information... Done
> Package libmysqlclient-dev is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'libmysqlclient-dev' has no installation candidate
> Skipping database if it exists
> ./install.sh: line 202: mysqlshow: command not found
> create database
> ./install.sh: line 210: mysql: command not found
> create db user friend
> ./install.sh: line 214: mysql: command not found
> ./install.sh: line 216: mysql: command not found
> ./install.sh: line 218: mysql: command not found
> create tables
> ./install.sh: line 222: mysql: command not found
> 
> =====Compilation process in progress...
> =========================================================
> ./install.sh: line 239: cd: friendup: No such file or directory
> ./install.sh: line 241: make: command not found
> ./install.sh: line 244: make: command not found
> =====Generating cfg.ini file...
> =========================================================
> ./install.sh: line 261: build/cfg/cfg.ini: No such file or directory
> ./install.sh: line 262: build/cfg/cfg.ini: No such file or directory

**Workaround:**
`apt install libmariadbclient-dev mariadb-client-10.1`
This seems to at least make that part of the script work, although at least once I got:
> create db user friend
> ERROR 1396 (HY000) at line 1: Operation DROP USER failed for 'friend'@'localhost'

The fact that it tries something with a user@'localhost' might indicate further problems, as the database server was specified by IP and is *not* on localhost.

**Suggestion:**
Terminate script on fatal errors, such as failure to install required packages, failure to set up the database, etc.

(there are still follow up errors, but I'll file separate issues for those once I understand what's happening and if they are related)

**Comment by titlestad** [comment]
Hey dm8tbr! :) Nice seeing you getting your hands dirty so quickly. Our test servers are usually Ubuntu based. I know stefkos uses Debian, but at least I'm on Linux Mint. May be Ubuntu has some packages that just aren't available on Debian as default. We'll have to look into this and make a more intelligent dependency script. We should start offering people debian packages, anyway - even though this doesn't fix your problem. Watch this space, and I'll get stefkos to post once we have a fix for you.

About localhost - we'll replicate this and get back to you here as well. Cheers by the way :+1:

**Comment by dm8tbr** [comment]
To reiterate the status quo:
The install.sh script doesn't handle dependency installation like on Ubuntu. This causes multiple issues.
So far I've identified mariadb (client/server/etc), build-essentials, openssl (headers), cmake.

**Comment by xet7** [comment]
There are dependencies missing from `install.sh` scripts, see install log.

[Example of adding dependencies for Ubuntu 18.04](https://github.com/Aperture-Development/friendup/commit/c18494f9e42cf4ba96c572ef66fa007ddcc8c284)

If you get modifications done to `install.sh` script so that some other distro also works, not just Ubuntu 16.04, please add pull request.

**Comment by titlestad** [comment]
Outdated.
