### ISSUE TITLE
UX/UI - Cursor

### ISSUE THREAD

**Issue by ghost** [FriendUPCloud/friendup#52]
Could we have a choice of left-handed cursor (or ambidextrous cursor pointing straight up) for 10% of users who are lefties? This usually gets overlooked by mainstream OSes! I love that the Amiga always let me create my own, so easily!

As Friend replaces the user's regular cursor, which may be customised for usability reasons, this seems like a sensible option. Size, shape and contrast of cursor are very important to some users, especially those with visual impairment.

**Comment by titlestad** [comment]
Yes. I'm actually left handed. But I prefer the normal cursor. But still, it's expected to be able to do this. The latest version has a theme settings tab for the FriendUP12 theme. I will add this option there.
