### ISSUE TITLE
UX/UI - Marketplace

### ISSUE THREAD

**Issue by RAMupgrade** [FriendUPCloud/friendup#53]
Viewing the market in landscape, on a non-1080p laptop seems VERY cramped! (I do have my browser at 120% with large fonts, because I have visual impairment. At 100% it's better but still cramped.)

The banner leaves little room for the actual apps. Suggest less banner space at the top and more room to scroll through apps. Or perhaps let the banner scroll up, just keeping the functional tabs on-screen.

**Comment by titlestad** [comment]
Thanks, this app is very early right now. Let's clean it up. :-)

**Comment by titlestad** [comment]
Fixed.
