### ISSUE TITLE
UX/UI - Menu bar

### ISSUE THREAD

**Issue by ghost** [FriendUPCloud/friendup#54]
Maybe the top menu bar on the desktop (system, window, clock, etc.) needs an icon -- to remind users that it can be dragged. It could even slide the screen when clicked. This feature isn't obvious to non-Amigans!

**Comment by titlestad** [comment]
Yes! Will be implemented for v1.2. Will add it in our sprint.

**Comment by titlestad** [comment]
Added in local repo. :-) So it's coming real soon. So that means before 1.2.
