### ISSUE TITLE
Friend Create v1.0.0 infinite add privileges window bug

### ISSUE THREAD

**Issue by m6502** [FriendUPCloud/friendup#61]
- Open Friend Create v1.0.0
- Click on Project Properties
- Click on Add Privileges
- Click on Project Properties Window to bring it to focus, and close the window
- The Add permission windows remains active and now you can't close it
- Bonus: You can generate an unlimited number of permission windows in this way :-)

![infinite add permission bug](https://user-images.githubusercontent.com/1667712/41111710-1a4727be-6a7d-11e8-9833-1eab922930cb.png)

**Comment by titlestad** [comment]
Fixed.
