### ISSUE TITLE
Menu bar bottom position bug (Friend Workspace v1.1.1)

### ISSUE THREAD

**Issue by m6502** [FriendUPCloud/friendup#63]
- Resize your web browser so there's screen space left on the bottom of your desktop.
- Drag the menu bar down... Don't stop at the web browser window, go further. The menu bar seems to follow the mouse all the way down.
- Release the menu bar.
- You are now stuck at the overview screen :-)
- If you resize the window you can find the menu bar, but you may have problems if you dragged past windows taskbar in a maximized window, or if you did this on a computer screen with a higher vertical resolution and moved the browser to a smaller screen.

Menu bar should not be possible to be drag down out of the visible space. 

If the visible space changes the menu bar should not get out of the view in any case. Maybe it could detect the special case of being at the bottom position and attach to the new bottom when detecting a change in vertical resolution?

Also possible to do if you drag to the bottom while the browser is in full screen mode then return to regular window view, and changing your screen resolution.

**Comment by arturlangner** [comment]
Thank you - bug confirmed. Internal reference BG-542.

**Comment by titlestad** [comment]
Is it still happening?
