### ISSUE TITLE
Friend Workspace v1.1.1: Actions menu bug

### ISSUE THREAD

**Issue by m6502** [FriendUPCloud/friendup#65]
- Click with the secondary button an icon that's not a folder, like Friend Workspace, Friend wizard, a normal file.
- Open folder is available.

![openfolder](https://user-images.githubusercontent.com/1667712/41165568-4733a344-6b3e-11e8-905b-c91a0415e8dc.png)

**Comment by titlestad** [comment]
Fixed.
