### ISSUE TITLE
Friend Workspace v1.1.1: Actions menu Open folder bug

### ISSUE THREAD

**Issue by m6502** [FriendUPCloud/friendup#66]
- Using "Open folder" in Actions menu triggers a "Compressing files" message.

![compressing files](https://user-images.githubusercontent.com/1667712/41165472-0f735134-6b3e-11e8-963c-d8ae79fcf035.png)

**Comment by titlestad** [comment]
Hmm, weird. How to reproduce? Just "Open folder"?

**Comment by titlestad** [comment]
Fixed. :-)
