### ISSUE TITLE
App Request: Add WinAmp Javascript version

### ISSUE THREAD

**Issue by xet7** [FriendUPCloud/friendup#68]
https://github.com/captbaritone/webamp

**Comment by titlestad** [comment]
Hey! I've added this to the local repository - but it's definately not playing nice with our Window management. WebAmp has its own window management, and requires a whole screen. Any idea how to work around this?

**Comment by Dr-Flay** [comment]
Perhaps the author may be interested in developing a FriendUP native version? There is not much competition, and if ported could easily become many peoples favoured player.

**Comment by titlestad** [comment]
I actually tried to build it for Friend, but it's written in a way that it doesn't want to be "floating". So I will close this for now. I hope the developer will consider it.
