### ISSUE TITLE
Unable to resize PDF windows in Chrome

### ISSUE THREAD

**Issue by andresclari** [FriendUPCloud/friendup#74]
Opening a PDF document, any from the documentation folder for instance, and trying to resize the window by the drag handle fails with just getting the scroll button clicked on Chrome.

However this works on Firefox.

Suggestion:
Maybe windows should have a transparent outer border, like on Windows, so you can drag from it, without getting that close to the actual window content.

Friend Version: v1.2 RC 1
Build Date: 20180919_092825

**Comment by titlestad** [comment]
We've expanded the resize gadget in the latest "dev" branch. Could you verify if this is still an issue?
