### ISSUE TITLE
Friend Native bypass iframe https restriction

### ISSUE THREAD

**Issue by andresclari** [FriendUPCloud/friendup#75]
While testing the system, I came up with the browser limitation of https.
I think it's quite important for a full system like this to be able to have a full internal browser even if not for everything.

For normal operation on traditional OS can't do much about it. But if a manually built version of Chromium or Firefox is to be used for the native distribution, it should have a setting to disable enforcing the iframe https policy, with a javascript hook so it can be controled from the Friend settings panel.

**Comment by stefkosdev** [comment]
Hey, we have plan to write our browser which will be based on existing ones. We will do our best to achieve that. I'm not sure if you know but we have also our own computer in our plans.

**Comment by 344Clinton** [comment]
There is a Chrome extension called [Ignore X-Frame headers](https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe) which will circumvent this issue. Note that this does create security risks that one should understand before using this method.

**Comment by titlestad** [comment]
Yes there are security risks. Sometimes I think it's crazy how much browsers try to close down possibilities for security, but that's what's happening. E.g. no raw sockets in Javascript.

Using an extension is one thing - but Friend cannot propose insecure solutions to users.

Making a HTML5 capable browser in pure Javascript or web assemblies is the true solution ;)

**Comment by titlestad** [comment]
We now have a solution in the works for this. I will close this issue because it is redundant :)
