### ISSUE TITLE
すごすぎる 🕷 is having problems with his new setup, no apps won't run after about about 30 clicks

### ISSUE THREAD

**Issue by AceZeroX** [FriendUPCloud/friendup#77]
すごすぎる 🕷
Applications did not start usually and instead I get
"Could not find application. Is it installed?"
![photo5296257428809165243](https://user-images.githubusercontent.com/17226693/46277657-12f13800-c564-11e8-8766-d1b22f778bae.jpg)
 after many clicks they start, but it takes time to click and pray.

すごすぎる 🕷:
Anything, doesn't meter
 Whatever I run
 Any program
 Need like 30 clicks to make it finally load
 Is not about specific program

すごすぎる 🕷:
16.04 Ubuntu
 Programs starts , but after lots of clicks on the icon

すごすぎる 🕷:
I'm not sure what does this mean
 on core startup
 (network/socket.c:781) 139791158933248 Cannot set
up connection with : pal.ideverket.no

すごすぎる 🕷
I'm not sure what does this mean
 on core startup
 (network/socket.c:781) 139791158933248 Cannot setup connection with : pal.ideverket.no
![photo5296407297397991697](https://user-images.githubusercontent.com/17226693/46277672-256b7180-c564-11e8-881f-cd1149ccc5e5.jpg)
ok here im about to start writer
 lots of pending
no time at all to login to the system
 if some of the team member interested in this bug I can give access to the server.
 I just make it to try

すごすぎる 🕷:
Thank you so much for replay. I have no time zone, constantly movie.
I have no https, only http
 Will give you account in a while to check
 No problem about password, just need good setup to show to my friends and convince them to use platform for our needs. Also investment is in a plan, but I need this system to work perfectly.

For more information and screenshots contact すごすぎる 🕷 on Telegram: https://web.telegram.org/#/im?p=@usr818 or contact me (Chris): https://web.telegram.org/#/im?p=@AceZeroX

Both of us have login to his server to try out.

**Comment by stefkosdev** [comment]
We are checking this.

**Comment by stefkosdev** [comment]
Websockets port was blocked.
