### ISSUE TITLE
"Connection has failed" message after connecting to the webpage localhost:6502

### ISSUE THREAD

**Issue by nax3n** [FriendUPCloud/friendup#79]
Hello, 

I have a "Connection has failed" message after connecting to the webpage localhost:6502. I don't figure it out. Here are some errors from my logs after launching ./Friendcore . Do you know why i get those errors ? 

Thanks.

`(network/http_client.c:253) 139866272733056 ERROR reading response from socket
[2019/01/04 09:09:18:6571] NOTICE: Creating Vhost 'default' port 6500, 4 protocols, IPv6 on

[2019/01/04 09:09:18.657465, 1] ssh_bind_import_keys:  Failed to import private DSA host key
 (ssh/ssh_server.c:694) 139865038014208 Error listening to socket: Failed to import private DSA host key
 139865046406912: [WS] Service will be started now

r: cannot open '/home/ubuntu/friendup/build/devices/DOSDrivers/INRam/dosdriver.ini'
  (system/fsys/dosdriver.c:106) 139866272733056 [ERROR]: Handler not found cannot create DOSDriver!

[2019/01/04 09:09:18:7036] NOTICE: Creating Vhost 'default' (serving disabled), 1 protocols, IPv6 on

ystembase.c:2300) 139866272733056 [SystemBase] MYSQL slot 8 was closed properly.
[2019/01/04 09:09:18:7050] NOTICE: Connect failed errno=111

(network/socket.c:771) 139864938903296 Cannot setup connection with : pal.ideverket.no

  (network/socket.c:771) 139864938903296 Cannot setup connection with : pal.ideverket.no
  (communication/comm_service.c:510) 139864938903296 FriendMasterServer found
  (core/friend_core.c:1706) 139866272733056 epoll event 1 sock 0x55bf68a451d0 - listen 60
  (core/friend_core.c:1706) 139866272733056 epoll event 1 sock 0x7f34b8000b40 - listen 60
  (core/friend_core.c:1706) 139866272733056 epoll event 1 sock 0x55bf68a451d0 - listen 60
  (core/friend_core.c:1706) 139866272733056 epoll event 1 sock 0x7f34b4000b20 - listen 60
  (core/friend_core.c:1706) 139866272733056 epoll event 1 sock 0x55bf68a451d0 - listen 60
  (core/friend_core.c:1706) 139866272733056 epoll event 1 sock 0x7f34a8000c80 - listen 60
 139866072192768: [ProtocolHttp] HTTP Callback called
139866072192768: INCOMING Request threads: 2 length: 350 data: GET / HTTP/1.1
Host: x.x.x.x:6502
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Connection: keep-alive
Upgrade-Insecure-Requests: 1

139866072192768: [ProtocolHttp] Request parsed without errors.
139866072192768: [ProtocolHttp] read static file /// size 3
139866072192768: [ProtocolHttp] Read single file, first from cache resources////
 (network/locfile.c:126) 139866072192768 'resources////' is a directory. Can not open.
 139866072192768: [ProtocolHttp] Return file content: file ptr (nil)`

**Comment by stefkosdev** [comment]
Please use link: localhost:6502/webclient/index.html
By using link localhost:6502 you are trying to get data which do not exist (check build/resource folder).

**Comment by nax3n** [comment]
Thanks it works now but why after the installation has completed it says "you can access your local machine at : http://localhost:6502" then.

Why there is a lot of errors on the logs like (network/socket.c:771) 139864938903296 Cannot setup connection with : pal.ideverket.no

**Comment by stefkosdev** [comment]
We dont want to maintain installer anymore. We created debian packages (debian/ubuntu) but they still didnt passed our all tests.
Our plan is to have one global server (pal.ideverket.no) which will be kind of base to our servers. Thats why FriendCore is trying to estabilish connection with it. Of course you can turn it off in code.

**Comment by thomaswollburg** [comment]
The wrong URL post-install is [now fixed](https://github.com/FriendUPCloud/friendup/commit/28fb4312a3c76e17aadf24446fde31208d12d078).
