### ISSUE TITLE
App Request: Add BassoonTracker for Amiga Mod files and FastTracker XM files

### ISSUE THREAD

**Issue by xet7** [FriendUPCloud/friendup#95]
https://github.com/steffest/bassoontracker

http://www.stef.be/bassoontracker/

**Comment by xet7** [comment]
Related HN discussion with some music:
https://news.ycombinator.com/item?id=19034690

**Comment by titlestad** [comment]
Fantastic suggestion! I will look into getting this built as a Friend application.

**Comment by titlestad** [comment]
This is now in pipe :-)
